//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.239
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_RESULT", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_RESULT : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string crudFieldField;
    
    private int reason_sortFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string crudField
    {
        get
        {
            return this.crudFieldField;
        }
        set
        {
            this.crudFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int reason_sortField
    {
        get
        {
            return this.reason_sortFieldField;
        }
        set
        {
            this.reason_sortFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="JOIN_ROOM_DETAIL", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class JOIN_ROOM_DETAIL : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int categoryFieldField;
    
    private string commentFieldField;
    
    private string durationFieldField;
    
    private uint indexFieldField;
    
    private int location_mainFieldField;
    
    private int location_subFieldField;
    
    private JOIN_ROOM_DETAILMEMBER_LIST mEMBER_LISTFieldField;
    
    private byte max_userFieldField;
    
    private string nameFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int categoryField
    {
        get
        {
            return this.categoryFieldField;
        }
        set
        {
            this.categoryFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string commentField
    {
        get
        {
            return this.commentFieldField;
        }
        set
        {
            this.commentFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string durationField
    {
        get
        {
            return this.durationFieldField;
        }
        set
        {
            this.durationFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint indexField
    {
        get
        {
            return this.indexFieldField;
        }
        set
        {
            this.indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_mainField
    {
        get
        {
            return this.location_mainFieldField;
        }
        set
        {
            this.location_mainFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_subField
    {
        get
        {
            return this.location_subFieldField;
        }
        set
        {
            this.location_subFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public JOIN_ROOM_DETAILMEMBER_LIST mEMBER_LISTField
    {
        get
        {
            return this.mEMBER_LISTFieldField;
        }
        set
        {
            this.mEMBER_LISTFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte max_userField
    {
        get
        {
            return this.max_userFieldField;
        }
        set
        {
            this.max_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string nameField
    {
        get
        {
            return this.nameFieldField;
        }
        set
        {
            this.nameFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="JOIN_ROOM_DETAILMEMBER_LIST", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class JOIN_ROOM_DETAILMEMBER_LIST : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private byte countFieldField;
    
    private byte joinableFieldField;
    
    private JOIN_ROOM_DETAILMEMBER_LISTMEMBER[] mEMBERFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte countField
    {
        get
        {
            return this.countFieldField;
        }
        set
        {
            this.countFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte joinableField
    {
        get
        {
            return this.joinableFieldField;
        }
        set
        {
            this.joinableFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public JOIN_ROOM_DETAILMEMBER_LISTMEMBER[] mEMBERField
    {
        get
        {
            return this.mEMBERFieldField;
        }
        set
        {
            this.mEMBERFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="JOIN_ROOM_DETAILMEMBER_LISTMEMBER", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class JOIN_ROOM_DETAILMEMBER_LISTMEMBER : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private byte ageFieldField;
    
    private byte genderFieldField;
    
    private string loginidFieldField;
    
    private string user_nameFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte ageField
    {
        get
        {
            return this.ageFieldField;
        }
        set
        {
            this.ageFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte genderField
    {
        get
        {
            return this.genderFieldField;
        }
        set
        {
            this.genderFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string loginidField
    {
        get
        {
            return this.loginidFieldField;
        }
        set
        {
            this.loginidFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string user_nameField
    {
        get
        {
            return this.user_nameFieldField;
        }
        set
        {
            this.user_nameFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="UPDATE_DEVICE_INFO", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class UPDATE_DEVICE_INFO : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string login_idFieldField;
    
    private int result_codeFieldField;
    
    private string user_noFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string login_idField
    {
        get
        {
            return this.login_idFieldField;
        }
        set
        {
            this.login_idFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int result_codeField
    {
        get
        {
            return this.result_codeFieldField;
        }
        set
        {
            this.result_codeFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string user_noField
    {
        get
        {
            return this.user_noFieldField;
        }
        set
        {
            this.user_noFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_INFO_LIST", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_INFO_LIST : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private ROOM_INFO_LISTROOM[] cREATE_INFOFieldField;
    
    private ROOM_INFO_LISTROOM1[] jOIN_INFOFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public ROOM_INFO_LISTROOM[] cREATE_INFOField
    {
        get
        {
            return this.cREATE_INFOFieldField;
        }
        set
        {
            this.cREATE_INFOFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public ROOM_INFO_LISTROOM1[] jOIN_INFOField
    {
        get
        {
            return this.jOIN_INFOFieldField;
        }
        set
        {
            this.jOIN_INFOFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_INFO_LISTROOM", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_INFO_LISTROOM : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int categoryFieldField;
    
    private string commentFieldField;
    
    private byte commitedFieldField;
    
    private byte current_userFieldField;
    
    private string durationFieldField;
    
    private uint indexFieldField;
    
    private bool is_dirtyFieldField;
    
    private bool is_dirtyFieldSpecifiedField;
    
    private int location_mainFieldField;
    
    private int location_subFieldField;
    
    private byte max_userFieldField;
    
    private string nameFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int categoryField
    {
        get
        {
            return this.categoryFieldField;
        }
        set
        {
            this.categoryFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string commentField
    {
        get
        {
            return this.commentFieldField;
        }
        set
        {
            this.commentFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte commitedField
    {
        get
        {
            return this.commitedFieldField;
        }
        set
        {
            this.commitedFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte current_userField
    {
        get
        {
            return this.current_userFieldField;
        }
        set
        {
            this.current_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string durationField
    {
        get
        {
            return this.durationFieldField;
        }
        set
        {
            this.durationFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint indexField
    {
        get
        {
            return this.indexFieldField;
        }
        set
        {
            this.indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public bool is_dirtyField
    {
        get
        {
            return this.is_dirtyFieldField;
        }
        set
        {
            this.is_dirtyFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public bool is_dirtyFieldSpecified
    {
        get
        {
            return this.is_dirtyFieldSpecifiedField;
        }
        set
        {
            this.is_dirtyFieldSpecifiedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_mainField
    {
        get
        {
            return this.location_mainFieldField;
        }
        set
        {
            this.location_mainFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_subField
    {
        get
        {
            return this.location_subFieldField;
        }
        set
        {
            this.location_subFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte max_userField
    {
        get
        {
            return this.max_userFieldField;
        }
        set
        {
            this.max_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string nameField
    {
        get
        {
            return this.nameFieldField;
        }
        set
        {
            this.nameFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_INFO_LISTROOM1", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_INFO_LISTROOM1 : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int categoryFieldField;
    
    private string commentFieldField;
    
    private byte commitedFieldField;
    
    private byte current_userFieldField;
    
    private string durationFieldField;
    
    private uint indexFieldField;
    
    private bool is_dirtyFieldField;
    
    private bool is_dirtyFieldSpecifiedField;
    
    private int location_mainFieldField;
    
    private int location_subFieldField;
    
    private byte max_userFieldField;
    
    private string nameFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int categoryField
    {
        get
        {
            return this.categoryFieldField;
        }
        set
        {
            this.categoryFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string commentField
    {
        get
        {
            return this.commentFieldField;
        }
        set
        {
            this.commentFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte commitedField
    {
        get
        {
            return this.commitedFieldField;
        }
        set
        {
            this.commitedFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte current_userField
    {
        get
        {
            return this.current_userFieldField;
        }
        set
        {
            this.current_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string durationField
    {
        get
        {
            return this.durationFieldField;
        }
        set
        {
            this.durationFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint indexField
    {
        get
        {
            return this.indexFieldField;
        }
        set
        {
            this.indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public bool is_dirtyField
    {
        get
        {
            return this.is_dirtyFieldField;
        }
        set
        {
            this.is_dirtyFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public bool is_dirtyFieldSpecified
    {
        get
        {
            return this.is_dirtyFieldSpecifiedField;
        }
        set
        {
            this.is_dirtyFieldSpecifiedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_mainField
    {
        get
        {
            return this.location_mainFieldField;
        }
        set
        {
            this.location_mainFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_subField
    {
        get
        {
            return this.location_subFieldField;
        }
        set
        {
            this.location_subFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte max_userField
    {
        get
        {
            return this.max_userFieldField;
        }
        set
        {
            this.max_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string nameField
    {
        get
        {
            return this.nameFieldField;
        }
        set
        {
            this.nameFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_SUMMARY_LIST", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_SUMMARY_LIST : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int categoryFieldField;
    
    private int location_mainFieldField;
    
    private int location_subFieldField;
    
    private ROOM_SUMMARY_LISTROOM_SUMMARY[] rOOM_SUMMARYFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int categoryField
    {
        get
        {
            return this.categoryFieldField;
        }
        set
        {
            this.categoryFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_mainField
    {
        get
        {
            return this.location_mainFieldField;
        }
        set
        {
            this.location_mainFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int location_subField
    {
        get
        {
            return this.location_subFieldField;
        }
        set
        {
            this.location_subFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public ROOM_SUMMARY_LISTROOM_SUMMARY[] rOOM_SUMMARYField
    {
        get
        {
            return this.rOOM_SUMMARYFieldField;
        }
        set
        {
            this.rOOM_SUMMARYFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ROOM_SUMMARY_LISTROOM_SUMMARY", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ROOM_SUMMARY_LISTROOM_SUMMARY : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string commentFieldField;
    
    private string durationFieldField;
    
    private uint indexFieldField;
    
    private byte max_userFieldField;
    
    private string nameFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string commentField
    {
        get
        {
            return this.commentFieldField;
        }
        set
        {
            this.commentFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string durationField
    {
        get
        {
            return this.durationFieldField;
        }
        set
        {
            this.durationFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint indexField
    {
        get
        {
            return this.indexFieldField;
        }
        set
        {
            this.indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public byte max_userField
    {
        get
        {
            return this.max_userFieldField;
        }
        set
        {
            this.max_userFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string nameField
    {
        get
        {
            return this.nameFieldField;
        }
        set
        {
            this.nameFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="CHAT_LIST", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class CHAT_LIST : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private CHAT_LISTCHAT[] cHATFieldField;
    
    private int countFieldField;
    
    private uint room_indexFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public CHAT_LISTCHAT[] cHATField
    {
        get
        {
            return this.cHATFieldField;
        }
        set
        {
            this.cHATFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int countField
    {
        get
        {
            return this.countFieldField;
        }
        set
        {
            this.countFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint room_indexField
    {
        get
        {
            return this.room_indexFieldField;
        }
        set
        {
            this.room_indexFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="CHAT_LISTCHAT", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class CHAT_LISTCHAT : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int chat_indexFieldField;
    
    private System.DateTime date_timeFieldField;
    
    private string nick_nameFieldField;
    
    private string valueFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int chat_indexField
    {
        get
        {
            return this.chat_indexFieldField;
        }
        set
        {
            this.chat_indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public System.DateTime date_timeField
    {
        get
        {
            return this.date_timeFieldField;
        }
        set
        {
            this.date_timeFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string nick_nameField
    {
        get
        {
            return this.nick_nameFieldField;
        }
        set
        {
            this.nick_nameFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string valueField
    {
        get
        {
            return this.valueFieldField;
        }
        set
        {
            this.valueFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="NOTICE_LIST", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class NOTICE_LIST : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int countFieldField;
    
    private string crudFieldField;
    
    private NOTICE_LISTNOTICE[] nOTICEFieldField;
    
    private int result_codeFieldField;
    
    private uint room_indexFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int countField
    {
        get
        {
            return this.countFieldField;
        }
        set
        {
            this.countFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string crudField
    {
        get
        {
            return this.crudFieldField;
        }
        set
        {
            this.crudFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public NOTICE_LISTNOTICE[] nOTICEField
    {
        get
        {
            return this.nOTICEFieldField;
        }
        set
        {
            this.nOTICEFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int result_codeField
    {
        get
        {
            return this.result_codeFieldField;
        }
        set
        {
            this.result_codeFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public uint room_indexField
    {
        get
        {
            return this.room_indexFieldField;
        }
        set
        {
            this.room_indexFieldField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="NOTICE_LISTNOTICE", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class NOTICE_LISTNOTICE : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private System.DateTime date_timeFieldField;
    
    private int indexFieldField;
    
    private string titleFieldField;
    
    private string valueFieldField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public System.DateTime date_timeField
    {
        get
        {
            return this.date_timeFieldField;
        }
        set
        {
            this.date_timeFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public int indexField
    {
        get
        {
            return this.indexFieldField;
        }
        set
        {
            this.indexFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string titleField
    {
        get
        {
            return this.titleFieldField;
        }
        set
        {
            this.titleFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string valueField
    {
        get
        {
            return this.valueFieldField;
        }
        set
        {
            this.valueFieldField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.studyheyo.co.kr", ConfigurationName="IRoom")]
public interface IRoom
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/Test", ReplyAction="http://www.studyheyo.co.kr/IRoom/TestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(RoomService.MyFaultException), Action="http://www.studyheyo.co.kr/IRoom/TestMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    ROOM_RESULT Test(string user_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/Test2", ReplyAction="http://www.studyheyo.co.kr/IRoom/Test2Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(RoomService.MyFaultException), Action="http://www.studyheyo.co.kr/IRoom/Test2MyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    string Test2(string user_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/GetLoginUser", ReplyAction="http://www.studyheyo.co.kr/IRoom/GetLoginUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(RoomService.MyFaultException), Action="http://www.studyheyo.co.kr/IRoom/GetLoginUserMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    JOIN_ROOM_DETAIL GetLoginUser();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/Push", ReplyAction="http://www.studyheyo.co.kr/IRoom/PushResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(RoomService.MyFaultException), Action="http://www.studyheyo.co.kr/IRoom/PushMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    ROOM_RESULT Push(string deviceToken, string Message, int badge);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/LoginUser", ReplyAction="http://www.studyheyo.co.kr/IRoom/LoginUserResponse")]
    bool LoginUser(string user_no, string login_id, string user_name, System.DateTime birth, byte gender, string deviceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/UpdateUserDevice", ReplyAction="http://www.studyheyo.co.kr/IRoom/UpdateUserDeviceResponse")]
    UPDATE_DEVICE_INFO UpdateUserDevice(string user_guid, string deviceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/CreateRoom", ReplyAction="http://www.studyheyo.co.kr/IRoom/CreateRoomResponse")]
    ROOM_RESULT CreateRoom(string user_no, RoomService.RoomSearchKey key, string name, string comment, string duration, int maxuser);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/MyRoomList", ReplyAction="http://www.studyheyo.co.kr/IRoom/MyRoomListResponse")]
    ROOM_INFO_LIST MyRoomList(string user_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/AllRoomList", ReplyAction="http://www.studyheyo.co.kr/IRoom/AllRoomListResponse")]
    ROOM_SUMMARY_LIST AllRoomList(RoomService.RoomSearchKey key, string user_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/JoinRoomDetail", ReplyAction="http://www.studyheyo.co.kr/IRoom/JoinRoomDetailResponse")]
    JOIN_ROOM_DETAIL JoinRoomDetail(uint room_index, string user_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/JoinRoom", ReplyAction="http://www.studyheyo.co.kr/IRoom/JoinRoomResponse")]
    ROOM_RESULT JoinRoom(string user_no, uint room_index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/LeaveRoom", ReplyAction="http://www.studyheyo.co.kr/IRoom/LeaveRoomResponse")]
    ROOM_RESULT LeaveRoom(string user_no, uint room_index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/CommitRoom", ReplyAction="http://www.studyheyo.co.kr/IRoom/CommitRoomResponse")]
    ROOM_RESULT CommitRoom(string user_no, uint room_index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/Chat", ReplyAction="http://www.studyheyo.co.kr/IRoom/ChatResponse")]
    CHAT_LIST Chat(uint room_index, string user_no, int last_update, string content);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/ChatUpdate", ReplyAction="http://www.studyheyo.co.kr/IRoom/ChatUpdateResponse")]
    CHAT_LIST ChatUpdate(uint room_index, string user_no, int last_update);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/CreateNotice", ReplyAction="http://www.studyheyo.co.kr/IRoom/CreateNoticeResponse")]
    NOTICE_LIST CreateNotice(uint room_index, string user_no, string title, string content);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/DeleteNotice", ReplyAction="http://www.studyheyo.co.kr/IRoom/DeleteNoticeResponse")]
    NOTICE_LIST DeleteNotice(uint room_index, string user_no, int notice_index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.studyheyo.co.kr/IRoom/UpdateNotice", ReplyAction="http://www.studyheyo.co.kr/IRoom/UpdateNoticeResponse")]
    NOTICE_LIST UpdateNotice(uint room_index, string user_no, int last_update);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRoomChannel : IRoom, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RoomClient : System.ServiceModel.ClientBase<IRoom>, IRoom
{
    
    public RoomClient()
    {
    }
    
    public RoomClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RoomClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RoomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RoomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ROOM_RESULT Test(string user_no)
    {
        return base.Channel.Test(user_no);
    }
    
    public string Test2(string user_no)
    {
        return base.Channel.Test2(user_no);
    }
    
    public JOIN_ROOM_DETAIL GetLoginUser()
    {
        return base.Channel.GetLoginUser();
    }
    
    public ROOM_RESULT Push(string deviceToken, string Message, int badge)
    {
        return base.Channel.Push(deviceToken, Message, badge);
    }
    
    public bool LoginUser(string user_no, string login_id, string user_name, System.DateTime birth, byte gender, string deviceToken)
    {
        return base.Channel.LoginUser(user_no, login_id, user_name, birth, gender, deviceToken);
    }
    
    public UPDATE_DEVICE_INFO UpdateUserDevice(string user_guid, string deviceToken)
    {
        return base.Channel.UpdateUserDevice(user_guid, deviceToken);
    }
    
    public ROOM_RESULT CreateRoom(string user_no, RoomService.RoomSearchKey key, string name, string comment, string duration, int maxuser)
    {
        return base.Channel.CreateRoom(user_no, key, name, comment, duration, maxuser);
    }
    
    public ROOM_INFO_LIST MyRoomList(string user_no)
    {
        return base.Channel.MyRoomList(user_no);
    }
    
    public ROOM_SUMMARY_LIST AllRoomList(RoomService.RoomSearchKey key, string user_no)
    {
        return base.Channel.AllRoomList(key, user_no);
    }
    
    public JOIN_ROOM_DETAIL JoinRoomDetail(uint room_index, string user_no)
    {
        return base.Channel.JoinRoomDetail(room_index, user_no);
    }
    
    public ROOM_RESULT JoinRoom(string user_no, uint room_index)
    {
        return base.Channel.JoinRoom(user_no, room_index);
    }
    
    public ROOM_RESULT LeaveRoom(string user_no, uint room_index)
    {
        return base.Channel.LeaveRoom(user_no, room_index);
    }
    
    public ROOM_RESULT CommitRoom(string user_no, uint room_index)
    {
        return base.Channel.CommitRoom(user_no, room_index);
    }
    
    public CHAT_LIST Chat(uint room_index, string user_no, int last_update, string content)
    {
        return base.Channel.Chat(room_index, user_no, last_update, content);
    }
    
    public CHAT_LIST ChatUpdate(uint room_index, string user_no, int last_update)
    {
        return base.Channel.ChatUpdate(room_index, user_no, last_update);
    }
    
    public NOTICE_LIST CreateNotice(uint room_index, string user_no, string title, string content)
    {
        return base.Channel.CreateNotice(room_index, user_no, title, content);
    }
    
    public NOTICE_LIST DeleteNotice(uint room_index, string user_no, int notice_index)
    {
        return base.Channel.DeleteNotice(room_index, user_no, notice_index);
    }
    
    public NOTICE_LIST UpdateNotice(uint room_index, string user_no, int last_update)
    {
        return base.Channel.UpdateNotice(room_index, user_no, last_update);
    }
}
namespace RoomService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomSearchKey", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    public partial struct RoomSearchKey : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _categoryField;
        
        private int _location_mainField;
        
        private int _location_subField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _category
        {
            get
            {
                return this._categoryField;
            }
            set
            {
                this._categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _location_main
        {
            get
            {
                return this._location_mainField;
            }
            set
            {
                this._location_mainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _location_sub
        {
            get
            {
                return this._location_subField;
            }
            set
            {
                this._location_subField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/RoomService")]
    public partial class MyFaultException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
}
