//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.269
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TradeSoap", Namespace="http://cjgamelab.co.kr/ws/hounds")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(XmlInfoBase))]
public partial class Trade : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetTradeListInfoOperationCompleted;
    
    /// <remarks/>
    public Trade() {
        this.Url = "http://dev.ws.hounds.cjgamelab.co.kr:8090/Trade.asmx";
    }
    
    /// <remarks/>
    public event GetTradeListInfoCompletedEventHandler GetTradeListInfoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cjgamelab.co.kr/ws/hounds/GetTradeListInfo", RequestNamespace="http://cjgamelab.co.kr/ws/hounds", ResponseNamespace="http://cjgamelab.co.kr/ws/hounds", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode GetTradeListInfo(TRADE_SEARCH_INFO trade_search_info) {
        object[] results = this.Invoke("GetTradeListInfo", new object[] {
                    trade_search_info});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTradeListInfo(TRADE_SEARCH_INFO trade_search_info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTradeListInfo", new object[] {
                    trade_search_info}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndGetTradeListInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void GetTradeListInfoAsync(TRADE_SEARCH_INFO trade_search_info) {
        this.GetTradeListInfoAsync(trade_search_info, null);
    }
    
    /// <remarks/>
    public void GetTradeListInfoAsync(TRADE_SEARCH_INFO trade_search_info, object userState) {
        if ((this.GetTradeListInfoOperationCompleted == null)) {
            this.GetTradeListInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTradeListInfoOperationCompleted);
        }
        this.InvokeAsync("GetTradeListInfo", new object[] {
                    trade_search_info}, this.GetTradeListInfoOperationCompleted, userState);
    }
    
    private void OnGetTradeListInfoOperationCompleted(object arg) {
        if ((this.GetTradeListInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTradeListInfoCompleted(this, new GetTradeListInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cjgamelab.co.kr/ws/hounds")]
public partial class TRADE_SEARCH_INFO : XmlInfoBase {
    
    private System.Nullable<int> item_indexField;
    
    private System.Nullable<byte> categoryField;
    
    private System.Nullable<byte> kindField;
    
    private System.Nullable<byte> sectionField;
    
    private System.Nullable<byte> item_rankField;
    
    private System.Nullable<byte> req_levelField;
    
    private System.Nullable<int> page_noField;
    
    private System.Nullable<int> page_sizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> item_index {
        get {
            return this.item_indexField;
        }
        set {
            this.item_indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<byte> category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<byte> kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<byte> section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<byte> item_rank {
        get {
            return this.item_rankField;
        }
        set {
            this.item_rankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<byte> req_level {
        get {
            return this.req_levelField;
        }
        set {
            this.req_levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> page_no {
        get {
            return this.page_noField;
        }
        set {
            this.page_noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> page_size {
        get {
            return this.page_sizeField;
        }
        set {
            this.page_sizeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TRADE_SEARCH_INFO))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cjgamelab.co.kr/ws/hounds")]
public abstract partial class XmlInfoBase {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetTradeListInfoCompletedEventHandler(object sender, GetTradeListInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTradeListInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTradeListInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}
